services:
  qe:
    image: ghcr.io/v4ldum/qe:latest
    restart: unless-stopped
    read_only: true
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    tmpfs:
        - /tmp:mode=0700,uid=101,gid=101
    healthcheck:
        # Draining
        test: /bin/test ! -f /tmp/drain # && some other healthcheck
        interval: 5s
        retries: 1
    networks:
      - netv6
    environment:
      - TZ=Europe/Paris
    labels:
      traefik.enable: true
      traefik.http.routers.qe.tls: true
      traefik.http.routers.qe.entrypoints: websecure
      traefik.http.routers.qe.rule: Host(`qe.valdum.dev`)

networks:
    netv6:
        name: netv6
        external: true
