server {
  listen 8080;
  listen [::]:8080;
  server_name localhost;
  root /usr/share/nginx/html;

  absolute_redirect off;

  location = / {
    return 301 /live/;
  }

  location /live/ {
    try_files $uri $uri/ /live/index.html;
  }
}
